- name: Configure HA
  hosts: ve_bigips
  connection: local
  gather_facts: false

  tasks:

  - name: Setting up provider values
    set_fact:
     provider:
      server: "{{inventory_hostname}}"
      server_port: "443"
      validate_certs: "False"
      
  - name: Device trust
    bigip_device_trust:
      provider: "{{provider}}"
      peer_server: "{{ peer_server }}"
      peer_hostname: "{{ peer_hostname }}"
      peer_user: "{{ peer_user }}"
      peer_password: "{{ peer_password }}"
     
  - pause:
      seconds: 30
      
  - name: Add Device Group
    bigip_device_group:
      provider: "{{provider}}"
      name: "deviceGrp"
      auto_sync: yes
      type: "sync-failover"

  - pause:
      seconds: 30
      
  - name: Add members to the device group
    bigip_device_group_member:
      provider: "{{provider}}"
      device_group: "deviceGrp"
      name: "{{ item }}"
      validate_certs: False
    loop:
      - "{{hostname}}"
      - "{{peer_hostname}}"

  - pause:
      seconds: 10
      
- name: Perform an initial sync of a device to a new device group
  bigip_configsync_action:
    device_group: new-device-group
    sync_device_to_group: yes
    provider:
      server: lb.mydomain.com
  delegate_to: localhost
  
